### ISSUE TITLE
Corrija esses problemas

### ISSUE THREAD

**Issue by DouglasVarollo** [Danielbraga1322/DevFinancee#1]
Vou citar quais são os problemas e já vou deixar o código corrigido.

- Esqueceu do sinal de atribuição na linha 21 do seu scripts.js
```js
const Storage = {
```
- Escreveu "amount" errado na linha 122 e 123 do seu index.html
```html
<input 
  type="number"
  step="0.01" 
  id="amount" 
  name="amount"
  placeholder="0,00"
/>
```
- Criou a variavel como "splitted" mas está usando ela como "splittedDate" na linha 123 do seu scripts.js
```js
const splittedDate = date.split("-")
return `${splittedDate[2]}/${splittedDate[1]}/${splittedDate[0]}}`
```
- Criou a variavel como "Transaction" mas está usando ela como "transaction" na linha 199 do seu scripts.js
```js
const transaction = Form.formatValues()      
Form.saveTransaction(transaction)
```
- Ficou uma chave "}" a mais no final da linha 123 do seu scripts.js 
```js
return `${splittedDate[2]}/${splittedDate[1]}/${splittedDate[0]}`
```

**Comment by Danielbraga1322** [comment]
Muito obrigado mais uma vez pela ajuda meu amigo!
Todas as correções funcionaram!
